export enum NotificationRouter {
  NAVIGATION_COMMENT_SCREEN = "NAVIGATION_COMMENT_SCREEN",
  NAVIGATION_CHAT_ROOM = "NAVIGATION_CHAT_ROOM",
  NAVIGATION_LIST_NOTIFICATIONS_SCREEN = "NAVIGATION_LIST_NOTIFICATIONS_SCREEN",
  NAVIGATION_PURCHASE_SUCCESS_SCREEN = "NAVIGATION_PURCHASE_SUCCESS_SCREEN",
  NAVIGATION_MESSAGE_SCREEN = "NAVIGATION_MESSAGE_SCREEN",
  NAVIGATION_LIKED_SCREEN = "NAVIGATION_LIKED_SCREEN",
  NAVIGATION_CLASS_ROOM = "NAVIGATION_CLASS_ROOM",
}

